spring:
  security:
    oauth2:
      client:
        registration:
          springboot-app:

            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          springboot-app:
            issuer-uri: https://auth.pgy.no-ip.hu/realms/code
